### ISSUE TITLE
View being cropped

### ISSUE THREAD

**Issue by jsnprofessor** [rjsvieira/circularView#3]
Hi, thanks for this convenient library. After using it in my project I found out that the circle gets cropped when arcWidth value is large enough. I was wondering if this was intentional.

**Comment by rjsvieira** [comment]
Hello @jsnprofessor 
Thank you for your feedback. Can you post a screenshot of said effect?
Regards,

**Comment by jsnprofessor** [comment]
<img width="469" alt="screen shot 2018-06-21 at 16 50 08" src="https://user-images.githubusercontent.com/11343333/41708748-091e29ea-7574-11e8-80a1-5a7585526e1b.png">
<img width="457" alt="screen shot 2018-06-21 at 16 55 51" src="https://user-images.githubusercontent.com/11343333/41708750-094af2cc-7574-11e8-9449-4a2136fbedba.png">

Heres the xml and result. Thanks for the support.

**Comment by rjsvieira** [comment]
Hello again
Increasing the width and height makes the cropping go away?
I'm not sure (at least without seeing the code) but I'm thinking the radius ratio of the arcWidth is causing the view to overlap its specified dimensions.

**Comment by asadqazi** [comment]
setting `app:arcWidth="xdp"` more than 10 makes this issue
I am also looking for a fix. if anyone have it fixed. Please share it

**Comment by asadqazi** [comment]
Here is the quick fix; I don't know is it a correct fix or not?
I increased the `private static int circlePadding = 25;` to `private static int circlePadding = 50;`
and then  `app:arcWidth="18dp"`. It worked like a charm

**Comment by jsnprofessor** [comment]
Thanks, will try it out later.

**Comment by asadqazi** [comment]
Progress bar starts at little back and overlaps with ending
